### PR TITLE
Kotiln version of plugin

### LINKED ISSUE #147: gradle build works once, fails on second attempt
Not sure if I'm doing something wrong, but here's a simple project to reproduce this behaviour.  "./gradlew build" works on the first run, but fails when run a second time because it cannot find the generated class.

```
/home/paul/projects/generated-sources-error/src/main/java/Test.java:1: error: package schema does not exist
import schema.Action;
             ^
/home/paul/projects/generated-sources-error/src/main/java/Test.java:5: error: cannot find symbol
        System.out.println(Action.VALUE_1);
                           ^
  symbol:   variable Action
  location: class Test
2 errors

FAILURE: Build failed with an exception.

```

[generated-sources-error.zip](https://github.com/jsonschema2dataclass/js2d-gradle/files/6882398/generated-sources-error.zip)

### PR DESCRIPTION
**Pull request by eirnym**
Fixes #147 and  #89

### CODE REVIEW

File: src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+    ) as Js2pGenerationTask
+
+    task.sourceFiles.setFrom(source)
+    task.configurationName = configurationName
+    task.uuid = UUID.randomUUID()
+    task.targetDirectory.set(
+            targetDirectoryPrefix.dir("${configurationName}$targetDirectorySuffix")
+    )
+    task.inputs.files({ task.sourceFiles.filter { it.exists() } }).skipWhenEmpty()
+    Files.walk(task.targetDirectory.get().asFile.toPath())
```
Comment (eirnym) [inline src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pPlugin.kt:233]: We don't cache the task and output should be cleaned always
